# sass-lint config (experimental)
#

files:
	include: '**/*.s+(a|c)ss'
options:
	formatter: stylish
	merge-default-rules: false
rules:
	class-name-format:
		- 1
		- convention: hyphenatedbem
	clean-import-paths:
		- 1
		- filename-extension: false
		- leading-underscore: false
	function-name-format:
		- 1
		- convention: hyphenatedlowercase
	hex-notation:
		- 1
		- style: lowercase
	id-name-format:
		- 1
		- convention: hyphenatedbem
	indentation:
		- 1
		- size: 1
	leading-zero:
		- 1
		- include: true
	mixin-name-format:
		- 1
		- convention: hyphenatedlowercase
	nesting-depth:
		- 1
		- max-depth: 4
	no-css-comments: 0
	no-mergeable-selectors: 0
	no-vendor-prefixes: 0
	placeholder-name-format:
		- 1
		- convention: hyphenatedbem
	property-sort-order: 0
	quotes:
		- 1
		- style: single
	shorthand-values: 1
	single-line-per-selector: 0
	space-after-colon: 1
	space-before-brace: 1
	url-quotes: 0
	variable-name-format:
		- 1
		- convention: hyphenatedlowercase
